Repository SOPT-TEAM6-Aladin/Aladin-iOS, pull requests merged in 2022-11, with the labels that each got.

#2 [Setting] #1 - 프로젝트 생성
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Aladin-iOS/Aladin-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Aladin-iOS/Aladin-iOS/AppDelegate.swift
  Aladin-iOS/Aladin-iOS/Assets.xcassets/AccentColor.colorset/Contents.json
  Aladin-iOS/Aladin-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  Aladin-iOS/Aladin-iOS/Assets.xcassets/Contents.json
  Aladin-iOS/Aladin-iOS/Base.lproj/LaunchScreen.storyboard
  Aladin-iOS/Aladin-iOS/Base.lproj/Main.storyboard
  Aladin-iOS/Aladin-iOS/Info.plist
  Aladin-iOS/Aladin-iOS/SceneDelegate.swift
  Aladin-iOS/Aladin-iOS/ViewController.swift
Labels: 수빈 🫶🏻, Add, Setting

#8 [Chore] #7 - 탭 바 뒤에 백그라운드 뷰 추가
  Aladin-iOS/Aladin-iOS/Screens/TabBar/MainTBC.swift
Labels: 수빈 🫶🏻, Chore, Design

#10 [Chore] #9 - 폰트 파일 에러 수정
  Aladin-iOS/Aladin-iOS/Info.plist
Labels: 수빈 🫶🏻, Fix

#11 [Feat] #5 - 도서 상세보기 뷰 레이아웃 구현
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS/Global/Literals/ImageLiterals.swift
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/aladinLogo.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/aladinLogo.imageset/Group.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/aladinLogo.imageset/Group@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/aladinLogo.imageset/Group@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/logo_letter.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/logo_letter.imageset/Vector.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/logo_letter.imageset/Vector@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/logo_letter.imageset/Vector@3x.png
  Aladin-iOS/Aladin-iOS/Screens/BookDetail/BookDetailVC.swift
  Aladin-iOS/Aladin-iOS/Screens/BookDetail/BookReviewTableViewCell.swift
  Aladin-iOS/Aladin-iOS/Screens/BookDetail/ReviewModel.swift
Labels: 인영 🫶🏻, Feat

#13 [Feat] #6 - 메인뷰 구현
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book2.imageset/book2.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book2.imageset/book2@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book2.imageset/book2@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_search.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Screens/Home/BookCVC.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/CategoryModel.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/ChoiceModel.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/EditerChoiceContainerView.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/HomeVC.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/HotBookCVC.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/HotBookContainerView.swift
  Aladin-iOS/Aladin-iOS/Screens/Home/HotBookModel.swift
Labels: 종화 🫶🏻, Feat

#16 [Feat] #12 - 장바구니 뷰 레이아웃 구현
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS/Global/Literals/ImageLiterals.swift
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image1.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image1.imageset/image 55.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image1.imageset/image 55@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image1.imageset/image 55@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image2.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image2.imageset/image 66.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image2.imageset/image 66@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/book_image2.imageset/image 66@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_active.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_active.imageset/Property 1=ic_check_active@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_inactive.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_inactive.imageset/Property 1=ic_check_inactive.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_inactive.imageset/Property 1=ic_check_inactive@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_check_inactive.imageset/Property 1=ic_check_inactive@3x.png
  Aladin-iOS/Aladin-iOS/Screens/Basket/BasketFooterView.swift
  Aladin-iOS/Aladin-iOS/Screens/Basket/BasketHeaderView.swift
  Aladin-iOS/Aladin-iOS/Screens/Basket/BasketModel.swift
  Aladin-iOS/Aladin-iOS/Screens/Basket/BasketTableViewCell.swift
  Aladin-iOS/Aladin-iOS/Screens/Basket/BasketVC.swift
  Aladin-iOS/Aladin-iOS/Screens/BookDetail/BookDetailVC.swift
Labels: 인영 🫶🏻, Feat

#17 Feat/#14 마이페이지뷰 구현
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS/Global/Literals/ColorLiterals.swift
  Aladin-iOS/Aladin-iOS/Global/Literals/ImageLiterals.swift
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame1.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame1.imageset/backFrame1.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame1.imageset/backFrame1@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame1.imageset/backFrame1@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame2.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame2.imageset/backFrame2.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame2.imageset/backFrame2@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame2.imageset/backFrame2@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame3.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame3.imageset/backFrame3.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame3.imageset/backFrame3@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/backFrame3.imageset/backFrame3@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_profile_color.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_profile_color.imageset/ic_colorProfile.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_profile_color.imageset/ic_colorProfile@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/ic_profile_color.imageset/ic_colorProfile@3x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/infoView.imageset/Contents.json
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/infoView.imageset/infoView.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/infoView.imageset/infoView@2x.png
  Aladin-iOS/Aladin-iOS/Global/Resources/Assets.xcassets/infoView.imageset/infoView@3x.png
  Aladin-iOS/Aladin-iOS/Screens/MyPage/ListModel.swift
  Aladin-iOS/Aladin-iOS/Screens/MyPage/ListTVC.swift
  Aladin-iOS/Aladin-iOS/Screens/MyPage/MyPageVC.swift
Labels: 종화 🫶🏻, Feat

#19 [Feat] #18 - 마이페이지뷰 푸터 구현
  Aladin-iOS/Aladin-iOS/Screens/MyPage/MyPageVC.swift
Labels: 종화 🫶🏻, Feat

#24 [Feat] #15- 네트워크 세팅 및 상세페이지 좋아요 api 연결
  Aladin-iOS/Aladin-iOS.xcodeproj/project.pbxproj
  Aladin-iOS/Aladin-iOS/Network/Base/APIConstants.swift
  Aladin-iOS/Aladin-iOS/Network/Base/Encodable+.swift
  Aladin-iOS/Aladin-iOS/Network/Base/NetworkLoggerPlugin.swift
  Aladin-iOS/Aladin-iOS/Network/DTO/BookLikeResponseDTO.swift
  Aladin-iOS/Aladin-iOS/Network/Router/BasketRouter.swift
  Aladin-iOS/Aladin-iOS/Network/Router/BookRouter.swift
  Aladin-iOS/Aladin-iOS/Screens/BookDetail/BookDetailVC.swift
Labels: 수빈 🫶🏻, Feat, Setting
